// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Module.Data;

#nullable disable

namespace Module.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    [Migration("20230509105713_sdssds")]
    partial class sdssds
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Module.Models.ActivityChaeson", b =>
                {
                    b.Property<int>("ActivityChaesonID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ActivityChaesonID"));

                    b.Property<string>("ActivityChaesonDetail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ActivityChaesonName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ActivityChaesonID");

                    b.ToTable("ActivityChaesons");
                });

            modelBuilder.Entity("Module.Models.LocationRest", b =>
                {
                    b.Property<int>("LocationRestID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LocationRestID"));

                    b.Property<string>("LocationRestName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LocationRestID");

                    b.ToTable("LocationRests");
                });

            modelBuilder.Entity("Module.Models.LocationTravel", b =>
                {
                    b.Property<int>("LocationTravelID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LocationTravelID"));

                    b.Property<string>("LocationTravelDetail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LocationTravelName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LocationTravelID");

                    b.ToTable("LocationTravels");
                });
#pragma warning restore 612, 618
        }
    }
}
